# Ndarray

The most important object defined in NumPy is an N-dimensional array type called ndarray. It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.

Every item in an ndarray takes the same size of block in the memory. Each element in ndarray is an object of data-type object (called dtype).

Any item extracted from ndarray object (by slicing) is represented by a Python object of one of array scalar types. The following diagram shows a relationship between ndarray, data type object (dtype) and array scalar type −

(NumPy'de tanımlanan en önemli nesne ndarray adı verilen N boyutlu bir dizi türüdür. Aynı türdeki öğelerin koleksiyonunu açıklar. Koleksiyondaki öğelere, sıfır temelli bir dizin kullanılarak erişilebilir.

Bir ndarray'deki her öğe, bellekteki aynı boyutta bloğu alır. Ndarray içindeki her öğe, veri türü nesnesinin bir nesnesidir (dtype olarak adlandırılır).

Ndarray nesnesinden çıkartılan herhangi bir öğe (dilimleme yoluyla) dizi skalar türlerinden birinin Python nesnesiyle temsil edilir. Aşağıdaki diyagram, ndarray, data type nesnesi (dtype) ve array skalar tipi arasındaki ilişkiyi gösterir -)

<img src="https://www.tutorialspoint.com/numpy/images/ndarray.jpg"
     alt="Markdown Monster icon"
     style="float: left; margin-right: 10px;" />

### numpy.array 
It creates an ndarray from any object exposing array interface, or from any method that returns an array.

(Herhangi bir nesne açığa çıkaran dizi arabiriminden veya bir dizi döndüren herhangi bir yöntemden bir ndarray oluşturur.)

numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

| Parameter   |      Description      |
|----------|:-------------:|
| object  |  Any object exposing the array interface method returns an array, or any (nested) sequence.(Dizi arabirim yöntemini açığa vuran herhangi bir nesne bir dizi veya herhangi bir (iç içe) dizi döndürür.)| 
| dtype |    Desired data type of array, optional (İstenilen veri dizisi türü, isteğe bağlı)   |
| copy | Optional. By default (true), the object is copied (İsteğe bağlı. Varsayılan olarak (true), nesne kopyalanır) |  
| order | C (row major) or F (column major) or A (any) (default) | 
| subok | By default, returned array forced to be a base class array. If true, sub-classes passed through (Varsayılan olarak, bir temel sınıf dizisi olmaya zorlanan diziyi döndürdü. Eğer doğruysa, alt sınıflar geçti) |
| ndmin | Specifies minimum dimensions of resultant array (Sonuç dizisinin minimum boyutlarını belirtir
) |

In [4]:
import numpy as np 
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
import numpy as np 
a = np.array([[1, 2], [3, 4]]) 
print(a)

[[1 2]
 [3 4]]


In [7]:
# minimum dimensions 
import numpy as np 
a = np.array([1,2,3,4,5])
b = np.array([1, 2, 3,4,5], ndmin = 2) 
print(a)
print(b)


[1 2 3 4 5]
[[1 2 3 4 5]]


In [8]:
# dtype parameter 
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print(a)

[1.+0.j 2.+0.j 3.+0.j]
