# NumPy - Array From Existing Data

## numpy.asarray
This function is similar to numpy.array except for the fact that it has fewer parameters. This routine is useful for converting Python sequence into ndarray.

(Daha az parametreye sahip olması dışında numpy.array e benzer. Python dizisini np dizisine dönüştürülmede kullanılır.)

numpy.asarray(a, dtype = None, order = None)

a =>
Input data in any form such as list, list of tuples, tuples, tuple of tuples or tuple of lists

dtype => 
By default, the data type of input data is applied to the resultant ndarray
	
order =>
C (row major) or F (column major). C is default

In [1]:
# convert list to ndarray 
import numpy as np 

x = [1,2,3] 
a = np.asarray(x) 
print (a)

[1 2 3]


In [2]:
# dtype is set 
import numpy as np 

x = [1,2,3]
a = np.asarray(x, dtype = float) 
print (a)

[1. 2. 3.]


In [5]:
# ndarray from list of tuples 
import numpy as np 

x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
print (a)

[(1, 2, 3) (4, 5)]


## numpy.frombuffer
This function interprets a buffer as one-dimensional array. Any object that exposes the buffer interface is used as parameter to return an ndarray.

(String ifadeyi numpy.array e dönüştürür.)

numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)

In [13]:
import numpy as np 
s = 'Hello World' 
a = np.frombuffer(s, dtype = 'S1') 
print (a)

AttributeError: 'str' object has no attribute '__buffer__'

## numpy.fromiter
This function builds an ndarray object from any iterable object. A new one-dimensional array is returned by this function.

numpy.fromiter(iterable, dtype, count = -1)

In [14]:
# create list object using range function 
import numpy as np 
list = range(5) 
print (list)
# obtain iterator object from list 
list = range(5) 
it = iter(list)  
# use iteator to create ndarray 
x = np.fromiter(it, dtype = float) 
print (x)

range(0, 5)
[0. 1. 2. 3. 4.]
