# NumPy - Array From Numerical Ranges

## numpy.arange
This function returns an ndarray object containing evenly spaced values within a given range. The format of the function is as follows −

(Başlangıç, bitiş, adım sayısı ve tipi verilen bir dizi oluşturur.)

numpy.arange(start, stop, step, dtype)


In [1]:
import numpy as np 
x = np.arange(5) 
print (x)

[0 1 2 3 4]


In [2]:
import numpy as np 
# dtype set 
x = np.arange(5, dtype = float)
print (x)

[0. 1. 2. 3. 4.]


In [4]:
# start and stop parameters set 
import numpy as np 
x = np.arange(10,20,2) 
print (x)

[10 12 14 16 18]


## numpy.linspace
This function is similar to arange() function. In this function, instead of step size, the number of evenly spaced values between the interval is specified. The usage of this function is as follows −

(Arange ye benzer. Adım boyutu yerine başlangiç ve bitiş noktası arası kaça bölüneceği verilir)

numpy.linspace(start, stop, num, endpoint, retstep, dtype)

In [5]:
import numpy as np 
x = np.linspace(10,20,5) 
print (x)

[10.  12.5 15.  17.5 20. ]


In [6]:
# endpoint set to false 
import numpy as np 
x = np.linspace(10,20, 5, endpoint = False) 
print (x)

[10. 12. 14. 16. 18.]


In [7]:
# find retstep value 
import numpy as np 

x = np.linspace(1,2,5, retstep = True) 
print (x)
# retstep here is 0.25

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


## numpy.logspace
This function returns an ndarray object that contains the numbers that are evenly spaced on a log scale. Start and stop endpoints of the scale are indices of the base, usually 10.

(Verilen base değerine göre başlangıç ve bitiş noktaları arasında base in üssü alınarak np dizisi oluşturulur. Num değeri başlangıç ve bitiş noktalarının kaç eşit parçaya bölüneceğini söyler.)

numpy.logspace(start, stop, num, endpoint, base, dtype)


In [8]:
import numpy as np 
# default base is 10 
a = np.logspace(1.0, 2.0, num = 10) 
print (a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [9]:
# set base of log space to 2 
import numpy as np 
a = np.logspace(1,10,num = 10, base = 2) 
print (a)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]
