# NumPy - Array Creation Routines

A new ndarray object can be constructed by any of the following array creation routines or using a low-level ndarray constructor.
(Yeni bir ndarray nesnesi, aşağıdaki dizi oluşturma yöntemlerinden herhangi biriyle veya düşük seviyeli bir ndarray yapıcısı kullanılarak oluşturulabilir.)

## numpy.empty
It creates an uninitialized array of specified shape and dtype. It uses the following constructor 
(Verilen boyutta sıfırla dolu yada verilen dtype tipinde sayılarda bir dizi oluşturur.)

In [19]:
import numpy as np 
x = np.empty([3,2])
print (x)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [20]:
import numpy as np 
x = np.empty([3,2], dtype = int)
print (x)

[[ 1376466032         493]
 [  411762395 -2147481744]
 [ 1381450760         493]]


## numpy.zeros
Returns a new array of specified size, filled with zeros.
(Sıfırlarla dolu, belirtilen boyutta yeni bir dizi döndürür.)

numpy.zeros(shape, dtype = float, order = 'C')

Shape =>
Shape of an empty array in int or sequence of int

Dtype =>
Desired output data type. Optional

Order =>
'C' for C-style row-major array, 'F' for FORTRAN style column-major array

In [21]:
# array of five zeros. Default dtype is float 
import numpy as np 
x = np.zeros(5) 
print (x)

[0. 0. 0. 0. 0.]


In [22]:
import numpy as np 
x = np.zeros((5,), dtype = np.int) 
print (x)

[0 0 0 0 0]


In [23]:
# custom type 
import numpy as np 
x = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print (x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


## numpy.ones
Returns a new array of specified size and type, filled with ones.

(belirtilen boyutta ve türde 1 lerden oluşan yeni bir dizi döndürür.)

numpy.ones(shape, dtype = None, order = 'C')

Shape => Shape of an empty array in int or sequence of int

Dtype => Desired output data type. Optional

Order => 'C' for C-style row-major array, 'F' for FORTRAN style column-major array

In [25]:
# array of five ones. Default dtype is float 
import numpy as np 
x = np.ones(5) 
print (x)

[1. 1. 1. 1. 1.]


In [27]:
import numpy as np 
x = np.ones([2,2], dtype = int) 
print (x)

[[1 1]
 [1 1]]
